import type { ComplianceCheckDef } from './types';

export const FRAMEWORK_LABELS: Record<string, string> = {
  RBI: 'RBI IT Governance',
  SEBI: 'SEBI Cybersecurity',
  SOC2: 'SOC 2 Trust Services',
  PCI_DSS: 'PCI-DSS v4.0',
};

export const COMPLIANCE_CHECKS: ComplianceCheckDef[] = [
  // ── Encryption (6 checks) ─────────────────────────────────────────
  {
    controlId: 'ENC-001',
    controlName: 'S3 Bucket Encryption at Rest',
    description: 'All S3 buckets must have server-side encryption enabled (SSE-S3 or SSE-KMS)',
    frameworks: ['RBI', 'SOC2', 'PCI_DSS'],
    severity: 'CRITICAL',
    category: 'Encryption',
    resourceType: 'S3 Bucket',
    provider: 'AWS',
    remediation: 'Enable default encryption on all S3 buckets using SSE-S3 or SSE-KMS',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'ENC-002',
    controlName: 'EBS Volume Encryption',
    description: 'All EBS volumes must be encrypted at rest',
    frameworks: ['RBI', 'PCI_DSS'],
    severity: 'CRITICAL',
    category: 'Encryption',
    resourceType: 'EBS Volume',
    provider: 'AWS',
    remediation: 'Enable EBS encryption by default in account settings and encrypt existing volumes',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'ENC-003',
    controlName: 'RDS Database Encryption',
    description: 'All RDS instances must have encryption at rest enabled',
    frameworks: ['RBI', 'SOC2', 'PCI_DSS'],
    severity: 'CRITICAL',
    category: 'Encryption',
    resourceType: 'RDS Instance',
    provider: 'AWS',
    remediation: 'Enable encryption when creating RDS instances. Existing unencrypted instances must be migrated',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'ENC-004',
    controlName: 'Data in Transit Encryption (TLS)',
    description: 'All data in transit must use TLS 1.2 or higher',
    frameworks: ['RBI', 'SEBI', 'SOC2', 'PCI_DSS'],
    severity: 'CRITICAL',
    category: 'Encryption',
    resourceType: 'Load Balancer',
    provider: 'AWS',
    remediation: 'Configure ALB/NLB listeners to use TLS 1.2+ and enforce HTTPS redirects',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'ENC-005',
    controlName: 'KMS Key Rotation',
    description: 'Customer-managed KMS keys must have automatic rotation enabled',
    frameworks: ['RBI', 'SOC2'],
    severity: 'HIGH',
    category: 'Encryption',
    resourceType: 'KMS Key',
    provider: 'AWS',
    remediation: 'Enable automatic key rotation for all customer-managed CMKs',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'ENC-006',
    controlName: 'Secrets Manager Usage',
    description: 'Application secrets must be stored in AWS Secrets Manager, not in code or environment variables',
    frameworks: ['SEBI', 'SOC2', 'PCI_DSS'],
    severity: 'HIGH',
    category: 'Encryption',
    resourceType: 'Secrets Manager',
    provider: 'AWS',
    remediation: 'Migrate hardcoded secrets to AWS Secrets Manager with automatic rotation',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },

  // ── Access Control (8 checks) ─────────────────────────────────────
  {
    controlId: 'IAM-001',
    controlName: 'MFA on Root Account',
    description: 'The AWS root account must have MFA enabled',
    frameworks: ['RBI', 'SEBI', 'SOC2', 'PCI_DSS'],
    severity: 'CRITICAL',
    category: 'Access Control',
    resourceType: 'IAM Root Account',
    provider: 'AWS',
    remediation: 'Enable hardware or virtual MFA on the root account immediately',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'IAM-002',
    controlName: 'IAM Password Policy',
    description: 'IAM password policy must require minimum 14 characters, uppercase, lowercase, numbers, and symbols',
    frameworks: ['RBI', 'SEBI', 'PCI_DSS'],
    severity: 'HIGH',
    category: 'Access Control',
    resourceType: 'IAM Policy',
    provider: 'AWS',
    remediation: 'Update IAM password policy to enforce complexity and 90-day rotation',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'IAM-003',
    controlName: 'Least Privilege Access',
    description: 'IAM policies must follow least privilege principle — no wildcard (*) resource permissions',
    frameworks: ['RBI', 'SOC2', 'PCI_DSS'],
    severity: 'HIGH',
    category: 'Access Control',
    resourceType: 'IAM Policy',
    provider: 'AWS',
    remediation: 'Review and restrict IAM policies to specific resources and actions',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'IAM-004',
    controlName: 'No Root Access Keys',
    description: 'Root account must not have active access keys',
    frameworks: ['RBI', 'SEBI', 'SOC2'],
    severity: 'CRITICAL',
    category: 'Access Control',
    resourceType: 'IAM Root Account',
    provider: 'AWS',
    remediation: 'Delete root access keys and use IAM users/roles for programmatic access',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'IAM-005',
    controlName: 'Access Key Rotation',
    description: 'IAM user access keys must be rotated every 90 days',
    frameworks: ['RBI', 'SEBI', 'PCI_DSS'],
    severity: 'HIGH',
    category: 'Access Control',
    resourceType: 'IAM User',
    provider: 'AWS',
    remediation: 'Implement access key rotation policy and deactivate keys older than 90 days',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'IAM-006',
    controlName: 'MFA for IAM Users',
    description: 'All IAM users with console access must have MFA enabled',
    frameworks: ['RBI', 'SEBI', 'SOC2', 'PCI_DSS'],
    severity: 'HIGH',
    category: 'Access Control',
    resourceType: 'IAM User',
    provider: 'AWS',
    remediation: 'Enforce MFA for all console users via IAM policy conditions',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'IAM-007',
    controlName: 'SSO Configuration',
    description: 'Enterprise SSO must be configured for centralized identity management',
    frameworks: ['RBI', 'SOC2'],
    severity: 'MEDIUM',
    category: 'Access Control',
    resourceType: 'IAM Identity Center',
    provider: 'AWS',
    remediation: 'Configure AWS IAM Identity Center with corporate IdP (Azure AD, Okta)',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'IAM-008',
    controlName: 'Session Timeout Policy',
    description: 'Console sessions must timeout after 15 minutes of inactivity',
    frameworks: ['SEBI', 'PCI_DSS'],
    severity: 'MEDIUM',
    category: 'Access Control',
    resourceType: 'IAM Policy',
    provider: 'AWS',
    remediation: 'Set maximum session duration to 1 hour and implement idle timeout',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },

  // ── Logging & Monitoring (8 checks) ───────────────────────────────
  {
    controlId: 'LOG-001',
    controlName: 'CloudTrail Enabled',
    description: 'AWS CloudTrail must be enabled in all regions for API activity logging',
    frameworks: ['RBI', 'SEBI', 'SOC2', 'PCI_DSS'],
    severity: 'CRITICAL',
    category: 'Logging & Monitoring',
    resourceType: 'CloudTrail',
    provider: 'AWS',
    remediation: 'Enable CloudTrail with multi-region trail and S3 log delivery',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'LOG-002',
    controlName: 'Multi-Region CloudTrail',
    description: 'CloudTrail must be configured as a multi-region trail',
    frameworks: ['SEBI', 'SOC2'],
    severity: 'HIGH',
    category: 'Logging & Monitoring',
    resourceType: 'CloudTrail',
    provider: 'AWS',
    remediation: 'Update CloudTrail configuration to enable multi-region logging',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'LOG-003',
    controlName: 'VPC Flow Logs',
    description: 'VPC flow logs must be enabled for all VPCs',
    frameworks: ['RBI', 'SEBI', 'SOC2', 'PCI_DSS'],
    severity: 'HIGH',
    category: 'Logging & Monitoring',
    resourceType: 'VPC',
    provider: 'AWS',
    remediation: 'Enable VPC flow logs for all VPCs with delivery to CloudWatch or S3',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'LOG-004',
    controlName: 'GuardDuty Enabled',
    description: 'Amazon GuardDuty must be enabled for threat detection',
    frameworks: ['SEBI', 'SOC2'],
    severity: 'HIGH',
    category: 'Logging & Monitoring',
    resourceType: 'GuardDuty',
    provider: 'AWS',
    remediation: 'Enable GuardDuty in all regions with findings exported to Security Hub',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'LOG-005',
    controlName: 'AWS Config Enabled',
    description: 'AWS Config must be enabled to track resource configuration changes',
    frameworks: ['RBI', 'SOC2'],
    severity: 'HIGH',
    category: 'Logging & Monitoring',
    resourceType: 'AWS Config',
    provider: 'AWS',
    remediation: 'Enable AWS Config in all regions with delivery to S3 and SNS notifications',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'LOG-006',
    controlName: 'S3 Access Logging',
    description: 'S3 buckets containing sensitive data must have access logging enabled',
    frameworks: ['RBI', 'PCI_DSS'],
    severity: 'MEDIUM',
    category: 'Logging & Monitoring',
    resourceType: 'S3 Bucket',
    provider: 'AWS',
    remediation: 'Enable server access logging for sensitive S3 buckets',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'LOG-007',
    controlName: 'ALB Access Logging',
    description: 'Application Load Balancers must have access logging enabled',
    frameworks: ['SEBI', 'SOC2'],
    severity: 'MEDIUM',
    category: 'Logging & Monitoring',
    resourceType: 'Load Balancer',
    provider: 'AWS',
    remediation: 'Enable ALB access logs with delivery to S3',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'LOG-008',
    controlName: 'CloudWatch Alarms',
    description: 'Critical metrics must have CloudWatch alarms configured',
    frameworks: ['SOC2', 'SEBI'],
    severity: 'MEDIUM',
    category: 'Logging & Monitoring',
    resourceType: 'CloudWatch',
    provider: 'AWS',
    remediation: 'Create CloudWatch alarms for unauthorized API calls, root login, and IAM policy changes',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },

  // ── Network Security (6 checks) ──────────────────────────────────
  {
    controlId: 'NET-001',
    controlName: 'No Default VPC Usage',
    description: 'Default VPC must not be used for production workloads',
    frameworks: ['RBI', 'SOC2', 'PCI_DSS'],
    severity: 'HIGH',
    category: 'Network Security',
    resourceType: 'VPC',
    provider: 'AWS',
    remediation: 'Create custom VPCs with proper CIDR ranges and subnet isolation',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'NET-002',
    controlName: 'No Unrestricted Security Groups',
    description: 'Security groups must not allow unrestricted inbound access (0.0.0.0/0)',
    frameworks: ['RBI', 'SEBI', 'SOC2', 'PCI_DSS'],
    severity: 'CRITICAL',
    category: 'Network Security',
    resourceType: 'Security Group',
    provider: 'AWS',
    remediation: 'Restrict security group rules to specific CIDR ranges and required ports only',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'NET-003',
    controlName: 'NACL Configuration',
    description: 'Network ACLs must be configured for subnet-level traffic filtering',
    frameworks: ['PCI_DSS', 'RBI'],
    severity: 'MEDIUM',
    category: 'Network Security',
    resourceType: 'Network ACL',
    provider: 'AWS',
    remediation: 'Configure custom NACLs for sensitive subnets with deny rules for unauthorized traffic',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'NET-004',
    controlName: 'WAF Enabled',
    description: 'AWS WAF must protect public-facing web applications',
    frameworks: ['SEBI', 'SOC2', 'PCI_DSS'],
    severity: 'HIGH',
    category: 'Network Security',
    resourceType: 'WAF',
    provider: 'AWS',
    remediation: 'Deploy AWS WAF with managed rule groups on all public ALBs and CloudFront distributions',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'NET-005',
    controlName: 'Private Subnets for Databases',
    description: 'Database instances must be deployed in private subnets only',
    frameworks: ['RBI', 'PCI_DSS'],
    severity: 'CRITICAL',
    category: 'Network Security',
    resourceType: 'RDS Instance',
    provider: 'AWS',
    remediation: 'Ensure all RDS instances are in private subnets with no public accessibility',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'NET-006',
    controlName: 'VPN/Direct Connect',
    description: 'Secure connectivity must be established via VPN or Direct Connect for on-premise integration',
    frameworks: ['RBI', 'SEBI'],
    severity: 'MEDIUM',
    category: 'Network Security',
    resourceType: 'VPN Gateway',
    provider: 'AWS',
    remediation: 'Set up AWS Site-to-Site VPN or Direct Connect for secure hybrid connectivity',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },

  // ── Backup & Recovery (5 checks) ──────────────────────────────────
  {
    controlId: 'BKP-001',
    controlName: 'RDS Automated Backups',
    description: 'RDS instances must have automated backups enabled with minimum 30-day retention',
    frameworks: ['RBI', 'SOC2'],
    severity: 'HIGH',
    category: 'Backup & Recovery',
    resourceType: 'RDS Instance',
    provider: 'AWS',
    remediation: 'Enable automated backups with 30-day retention period for all RDS instances',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'BKP-002',
    controlName: 'S3 Versioning',
    description: 'Critical S3 buckets must have versioning enabled',
    frameworks: ['RBI', 'SOC2'],
    severity: 'MEDIUM',
    category: 'Backup & Recovery',
    resourceType: 'S3 Bucket',
    provider: 'AWS',
    remediation: 'Enable versioning on all S3 buckets storing critical or compliance data',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'BKP-003',
    controlName: 'Cross-Region Replication',
    description: 'Critical data must be replicated to a secondary region for disaster recovery',
    frameworks: ['RBI', 'SEBI'],
    severity: 'HIGH',
    category: 'Backup & Recovery',
    resourceType: 'S3 Bucket',
    provider: 'AWS',
    remediation: 'Configure cross-region replication for critical S3 buckets and RDS read replicas',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'BKP-004',
    controlName: 'Backup Retention Policy',
    description: 'Backup retention must be at least 30 days for regulatory compliance',
    frameworks: ['RBI', 'SEBI', 'PCI_DSS'],
    severity: 'HIGH',
    category: 'Backup & Recovery',
    resourceType: 'AWS Backup',
    provider: 'AWS',
    remediation: 'Configure AWS Backup with lifecycle policies ensuring 30-day minimum retention',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'BKP-005',
    controlName: 'Disaster Recovery Plan',
    description: 'A documented and tested disaster recovery plan must exist',
    frameworks: ['RBI', 'SEBI', 'SOC2'],
    severity: 'HIGH',
    category: 'Backup & Recovery',
    resourceType: 'Organization',
    provider: 'AWS',
    remediation: 'Document DR plan with RPO/RTO targets and conduct quarterly DR drills',
    evaluate: () => 'FAIL',
  },

  // ── Data Protection (6 checks) ────────────────────────────────────
  {
    controlId: 'DAT-001',
    controlName: 'Data Classification Tags',
    description: 'All resources must have data classification tags (Public, Internal, Confidential, Restricted)',
    frameworks: ['RBI', 'SEBI', 'SOC2'],
    severity: 'HIGH',
    category: 'Data Protection',
    resourceType: 'All Resources',
    provider: 'AWS',
    remediation: 'Implement mandatory DataClassification tag via AWS Organizations SCP',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'DAT-002',
    controlName: 'No Public S3 Buckets',
    description: 'S3 buckets must not have public access enabled',
    frameworks: ['RBI', 'SEBI', 'SOC2', 'PCI_DSS'],
    severity: 'CRITICAL',
    category: 'Data Protection',
    resourceType: 'S3 Bucket',
    provider: 'AWS',
    remediation: 'Enable S3 Block Public Access at account level and remove public bucket policies',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'DAT-003',
    controlName: 'No Public RDS Instances',
    description: 'RDS instances must not be publicly accessible',
    frameworks: ['RBI', 'PCI_DSS'],
    severity: 'CRITICAL',
    category: 'Data Protection',
    resourceType: 'RDS Instance',
    provider: 'AWS',
    remediation: 'Disable public accessibility on all RDS instances',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'DAT-004',
    controlName: 'Deletion Protection',
    description: 'Production databases and critical resources must have deletion protection enabled',
    frameworks: ['SOC2', 'RBI'],
    severity: 'HIGH',
    category: 'Data Protection',
    resourceType: 'RDS Instance',
    provider: 'AWS',
    remediation: 'Enable deletion protection on all production RDS instances and DynamoDB tables',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'DAT-005',
    controlName: 'Macie for Sensitive Data Discovery',
    description: 'Amazon Macie should be enabled for automated sensitive data discovery in S3',
    frameworks: ['RBI', 'PCI_DSS'],
    severity: 'MEDIUM',
    category: 'Data Protection',
    resourceType: 'Macie',
    provider: 'AWS',
    remediation: 'Enable Amazon Macie to automatically discover and protect sensitive data',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'DAT-006',
    controlName: 'Data Residency — India Region',
    description: 'Primary data must reside in ap-south-1 (Mumbai) for Indian regulatory compliance',
    frameworks: ['RBI'],
    severity: 'CRITICAL',
    category: 'Data Protection',
    resourceType: 'Infrastructure',
    provider: 'AWS',
    remediation: 'Ensure all primary data storage (RDS, S3, DynamoDB) is in ap-south-1',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },

  // ── Compliance-Specific (6 checks) ────────────────────────────────
  {
    controlId: 'PCI-001',
    controlName: 'PCI Network Segmentation',
    description: 'Cardholder data environment must be segmented from other networks',
    frameworks: ['PCI_DSS'],
    severity: 'CRITICAL',
    category: 'Compliance Specific',
    resourceType: 'VPC',
    provider: 'AWS',
    remediation: 'Implement separate VPCs/subnets for CDE with strict security group rules',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'PCI-002',
    controlName: 'PCI Cardholder Data Encryption',
    description: 'Primary Account Numbers must be rendered unreadable anywhere they are stored',
    frameworks: ['PCI_DSS'],
    severity: 'CRITICAL',
    category: 'Compliance Specific',
    resourceType: 'Application',
    provider: 'AWS',
    remediation: 'Implement field-level encryption for PAN data using KMS-managed keys',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'SEBI-001',
    controlName: 'Incident Response Plan',
    description: 'A documented cyber incident response plan must be maintained and tested',
    frameworks: ['SEBI', 'SOC2'],
    severity: 'HIGH',
    category: 'Compliance Specific',
    resourceType: 'Organization',
    provider: 'AWS',
    remediation: 'Create and maintain IRP with defined roles, communication plan, and quarterly testing',
    evaluate: () => 'FAIL',
  },
  {
    controlId: 'SEBI-002',
    controlName: 'Vulnerability Scanning',
    description: 'Regular vulnerability scans must be conducted on all public-facing assets',
    frameworks: ['SEBI', 'PCI_DSS'],
    severity: 'HIGH',
    category: 'Compliance Specific',
    resourceType: 'EC2 Instance',
    provider: 'AWS',
    remediation: 'Enable Amazon Inspector for automated vulnerability scanning of EC2 and ECR',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'SOC2-001',
    controlName: 'Change Management Process',
    description: 'All infrastructure changes must go through a documented change management process',
    frameworks: ['SOC2'],
    severity: 'HIGH',
    category: 'Compliance Specific',
    resourceType: 'Organization',
    provider: 'AWS',
    remediation: 'Implement IaC (Terraform/CloudFormation) with PR reviews and CI/CD pipelines',
    evaluate: () => 'PASS',
  },
  {
    controlId: 'SOC2-002',
    controlName: 'Availability Monitoring',
    description: 'Production systems must have uptime monitoring with automated alerting',
    frameworks: ['SOC2'],
    severity: 'HIGH',
    category: 'Compliance Specific',
    resourceType: 'CloudWatch',
    provider: 'AWS',
    remediation: 'Configure CloudWatch synthetics canaries and Route 53 health checks with SNS alerts',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },

  // ── Operational (5 checks) ────────────────────────────────────────
  {
    controlId: 'OPS-001',
    controlName: 'Resource Tagging Standards',
    description: 'All resources must have mandatory tags: Environment, Application, Owner, CostCenter',
    frameworks: ['RBI', 'SOC2'],
    severity: 'MEDIUM',
    category: 'Operational',
    resourceType: 'All Resources',
    provider: 'AWS',
    remediation: 'Implement AWS Organizations tag policies and enforce via SCP',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'OPS-002',
    controlName: 'Cost Allocation Tags',
    description: 'Cost allocation tags must be activated for accurate cost attribution',
    frameworks: ['SOC2'],
    severity: 'MEDIUM',
    category: 'Operational',
    resourceType: 'Billing',
    provider: 'AWS',
    remediation: 'Activate cost allocation tags in AWS Billing console for CostCenter and Environment',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'OPS-003',
    controlName: 'Budget Alerts Configured',
    description: 'AWS Budgets must be configured with threshold alerts',
    frameworks: ['SOC2', 'RBI'],
    severity: 'MEDIUM',
    category: 'Operational',
    resourceType: 'Budgets',
    provider: 'AWS',
    remediation: 'Create AWS Budgets with 50%, 80%, and 100% threshold alerts',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'OPS-004',
    controlName: 'Auto Scaling Configuration',
    description: 'Production workloads must use Auto Scaling for availability and cost optimization',
    frameworks: ['SOC2'],
    severity: 'MEDIUM',
    category: 'Operational',
    resourceType: 'Auto Scaling Group',
    provider: 'AWS',
    remediation: 'Configure Auto Scaling groups with appropriate min/max capacity and scaling policies',
    evaluate: (ctx) => ctx.awsConnected ? 'PASS' : 'NOT_APPLICABLE',
  },
  {
    controlId: 'OPS-005',
    controlName: 'Patch Management',
    description: 'EC2 instances must have automated patch management via Systems Manager',
    frameworks: ['SEBI', 'SOC2', 'PCI_DSS'],
    severity: 'HIGH',
    category: 'Operational',
    resourceType: 'EC2 Instance',
    provider: 'AWS',
    remediation: 'Enable AWS Systems Manager Patch Manager with maintenance windows',
    evaluate: (ctx) => ctx.awsConnected ? 'FAIL' : 'NOT_APPLICABLE',
  },
];
